# User.destroy_all
# Match.destroy_all

User.create!([
  { first_name: "Elisheva", last_name: "Birch", email: "elisheva@example.com", password_digest: "$2a$12$q81.wkeCAkIOKJdHbz69uOGyw/lr63SCx7TJHEX8Oo5CmibCsW6ve", gender: "F", birthday: "2000-06-02", address: "1198 East 16 Street", phone_number: "917-334-6436", currently_doing: "Working in an ambulance office", education: "Brooklyn College ", references: "", additional_info: nil, admin: false, image_url: "https://previews.123rf.com/images/vectorkif/vectorkif1902/vectorkif190200052/116556273-face-expression-of-woman-in-blue-blouse-happy-female-emotion-beautiful-cartoon-character-vector-illu.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "The", last_name: "Shadchan", email: "theshadchan@example.com", password_digest: "$2a$12$Ou7w8Wi0s2GSaW2f.21B7eGHBlLxdg9OyXaQRKr0gSf9QVIaOoTde", gender: "F", birthday: "a date", address: nil, phone_number: nil, currently_doing: nil, education: nil, references: nil, additional_info: nil, admin: true, image_url: nil, parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Mimi", last_name: "Ramp", email: "mimi@example.com", password_digest: "$2a$12$4cgd/4Y6j81Jc0aGz1ECze9JOAQc1ojGz7kXqRP/TwenJpQdA0FIS", gender: "F", birthday: "2000-12-27", address: "Woodmere, NY", phone_number: "516-029-9987", currently_doing: "Assisting the elderly ", education: "TAG", references: "Roommate - 516-923-0043", additional_info: nil, admin: false, image_url: "https://i.pinimg.com/originals/bb/29/fc/bb29fc998f831b8b2020869e6bb24cbe.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Esther", last_name: "Kochen", email: "esther@example.com", password_digest: "$2a$12$LFxjEw4dvY5sV8UZwLR8wuBy3qF7gBGjtY9WKCvobddGHYZO.USPe", gender: "F", birthday: "1997-12-01", address: "786 Sesame Street", phone_number: "111-111-1111", currently_doing: "Touro College", education: "Touro College", references: "Pricipal 718-223-2500", additional_info: nil, admin: false, image_url: "https://image.shutterstock.com/image-vector/female-silhoutte-avatar-default-profile-260nw-1219366543.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Aviva", last_name: "Slater", email: "slater@example.com", password_digest: "$2a$12$HY5IdunRIeFEcD4snnv.L.VNBJEboXYN64.E9S3sp2ohGtelQMu/a", gender: "F", birthday: "1998-02-29", address: "312 Ave R.", phone_number: "718-221-9204", currently_doing: "Secretary in Doctor's Office", education: "BY", references: "Doctor - 718-991-2915", additional_info: "", admin: false, image_url: "https://image.shutterstock.com/image-vector/beautiful-young-teenager-happy-girl-260nw-380863648.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Tami", last_name: "Plier", email: "tami@example.com", password_digest: "$2a$12$Gx2Ago8bKinXyx6CgXIFw.dUcnQLxPKvILU8Nam13zCk6OLg1usqe", gender: "F", birthday: "2001-02-27", address: "Highland Park, New Jersey ", phone_number: "732-331-9201", currently_doing: "Pursuing a Bachelors Degree in Psychology", education: "NYU", references: "High School Principal - 7182278827", additional_info: "Offering support", admin: false, image_url: "https://image.shutterstock.com/image-vector/female-silhoutte-avatar-default-profile-260nw-1219366543.jpg", parents: nil, siblings: nil, shul: "some", summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Shaindy", last_name: "Silver", email: "shaindy@example.com", password_digest: "$2a$12$TE9g4dwaZrBUQyRzPIFqHehHqdD7tlUfpGjgrBb/7Vq4Ibm3Xymk.", gender: "F", birthday: "2001-11-27", address: "12 Kentucky Place", phone_number: "928-453-2888", currently_doing: nil, education: "Pursuing BS in CS in LAS", references: "Mrs. Katz - 718-660-5434", additional_info: nil, admin: false, image_url: "https://image.shutterstock.com/image-vector/female-silhoutte-avatar-default-profile-260nw-1219366543.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Sarah", last_name: "Bee", email: "sarah@example.com", password_digest: "$2a$12$blJFKmhD1rK2jQWSwdpBquLK0gmIjbchgjp9YkN1hB2uyrYDWcZ/S", gender: "F", birthday: "1995-12-27", address: "299 Huckleberry Drive", phone_number: "347-855-6099", currently_doing: "Teacher's Assistant in Nursery ", education: nil, references: "", additional_info: "looking support", admin: false, image_url: "https://image.shutterstock.com/image-vector/female-silhoutte-avatar-default-profile-260nw-1219366543.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Chezkie", last_name: "Klein", email: "chezkie@example.com", password_digest: "$2a$12$h8mKzJCIQH6wXjyjE4BKl.dL1T1ufDvSd8RKMApOZ9xSuez5y.Z6a", gender: "M", birthday: "1999-12-27", address: "Brooklyn, NY", phone_number: "917-478-2660", currently_doing: "In between jobs ", education: "YU", references: "Family Friend - 347-862-1892", additional_info: "Allergic to dairy ", admin: false, image_url: "https://thumbs.dreamstime.com/b/male-silhoutte-avatar-default-profile-picture-photo-placeholder-vector-illustration-130555183.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Leora", last_name: "K", email: "leora@example.com", password_digest: "$2a$12$zKNKTSEboU/u.1Qsqqha4e3U/QTMLSqlE1My/ofAIjp4VpIlCA4Sm", gender: "boy", birthday: "06/06/1998", address: "124 Sesame Street", phone_number: "111-111-1111", currently_doing: "undecided ", education: nil, references: nil, additional_info: "looking support", admin: false, image_url: nil, parents: nil, siblings: nil, shul: nil, summers: nil, height: "5\"7", shadchan_info: nil, looking_for: "solid working boy", machatonim: nil },
  { first_name: "test", last_name: "Test", email: "test@example.com", password_digest: "$2a$12$Wk/ULofoA0z5PaGb8f8KOOHZWF5j/AKpTTer5MOZrM1bQy.WhUDrm", gender: "F", birthday: "3003-03-02", address: "13 plain area", phone_number: "492049", currently_doing: "learning", education: "skwls", references: "people", additional_info: "hot stuff", admin: false, image_url: "https://image.shutterstock.com/image-vector/female-silhoutte-avatar-default-profile-260nw-1219366543.jpg", parents: "nice people", siblings: "cool kids ", shul: "tc", summers: "camps", height: "5''3", shadchan_info: "diabities", looking_for: "good boy ", machatonim: nil },
  { first_name: "Mike", last_name: "Bene", email: "mike@example.com", password_digest: "$2a$12$iD5dLDEww/rP/ygq.P0EXutV8.8RgJqk5hDkxgkrr9pHKRVHZQSWW", gender: "M", birthday: "2000-03-02", address: "new york ", phone_number: "324-444-1090", currently_doing: "learning", education: "bmg", references: "", additional_info: "", admin: false, image_url: "https://www.dlf.pt/png/big/0/8993_man-cartoon-png.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Rikki", last_name: "Berger", email: "rikki@example.com", password_digest: "$2a$12$pgEXJ6qzIQKxYZHA3BwUkuwTYMwlZ7xR4WPePTM09vKKQrGM459oa", gender: "F", birthday: "1979-12-27", address: "123 Sesame Street", phone_number: "111-111-1111", currently_doing: "Persuing a degree in nursing from Brooklyn College ", education: "", references: "Tzipora 917-899-2407", additional_info: "Warm, nice family ", admin: false, image_url: "https://image.shutterstock.com/image-vector/face-expression-beautiful-blonde-woman-260nw-1686838690.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Rache", last_name: "Kass", email: "rache@example.com", password_digest: "$2a$12$lsp8wm.UNyLg61kR9wG/MOQoOAzliYTYeUZUROkyQ4Y4qnAFOrOq.", gender: "F", birthday: "2001-10-16", address: "Cederhurst", phone_number: "111-222-3333", currently_doing: "being a morah", education: "bymr for the winnnn", references: "tzip obv ", additional_info: "", admin: false, image_url: "https://image.shutterstock.com/image-vector/beautiful-brunette-girl-dark-chocolate-260nw-577283176.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Aviva", last_name: "Tanner", email: "aviva@example.com", password_digest: "$2a$12$VuEPCawqCGS.fGU76QMjzOPtHRQxCsT/g1SH/A59E4.zc2krOUhgm", gender: "F", birthday: "2000-04-15", address: "In Monsey", phone_number: "311-646-8841", currently_doing: "Makeup Artist ", education: "NYC School of Makeup ", references: "Aunt - 322-432-6334", additional_info: "Loves children", admin: false, image_url: "https://image.shutterstock.com/image-vector/female-silhoutte-avatar-default-profile-260nw-1219366543.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Daniel", last_name: "Nor", email: "daniel@example.com", password_digest: "$2a$12$oZ3jep5mu665tXd6WX65ouMFy6HdOVwTd03x6OJzg4XMG27PMyzuS", gender: "M", birthday: "1997-09-26", address: "house in brooklyn", phone_number: "", currently_doing: "", education: "", references: "", additional_info: "", admin: false, image_url: "https://thumbs.dreamstime.com/b/male-silhoutte-avatar-default-profile-picture-photo-placeholder-vector-illustration-130555183.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Adina", last_name: "Stein", email: "adina@example.com", password_digest: "$2a$12$bM1iji4Xow8JaTTbcaJ8eOoy3GQGIYK4woJH1wENhva6Qen8aDEH.", gender: "F", birthday: "2000-12-11", address: "Lawrence, NY", phone_number: "516-325-6632", currently_doing: "In TTI College ", education: "BC", references: "principal - 345-666-5732", additional_info: "", admin: false, image_url: "https://static8.depositphotos.com/1002015/802/v/600/depositphotos_8025102-stock-illustration-blond-cowgirl-with-lasso.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Josh", last_name: "Birn", email: "josh@example.com", password_digest: "$2a$12$f.J/vsXe4pzQgDtMT.vDBuVo.8aoOa96OQCNAF5ajyMhctmab6m6a", gender: "M", birthday: "1999-10-27", address: "124 Another Street", phone_number: "321-233-2532", currently_doing: "Learning ", education: "YSV", references: nil, additional_info: "loves hiking ", admin: false, image_url: "https://thumbs.dreamstime.com/b/male-silhoutte-avatar-default-profile-picture-photo-placeholder-vector-illustration-130555183.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Daniel", last_name: "Kalsh", email: "d@example.com", password_digest: "$2a$12$gLHp6TRFUtCz.4ZMBzxDeOPUruNg2Zr4VsSNLjLUWMWKQGqjFSCWm", gender: "M", birthday: "1998-02-22", address: "Monsey, NY", phone_number: "845-829-2145", currently_doing: "Learning", education: "BMG", references: "Rebbe - 917-493-6656", additional_info: "Long term learner", admin: false, image_url: "https://image.shutterstock.com/z/stock-vector-cute-cartoon-boy-with-blond-hair-wearing-glasses-blue-jumper-white-shirt-and-grey-trousers-is-348674033.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Abe", last_name: "Klein", email: "abe@example.com", password_digest: "$2a$12$wskyiBO/TdPEuzM7FKV07.4TbcjsABbDy8GwDzwiDp1FBiT69Kl3a", gender: "M", birthday: "2000-01-27", address: "786 Sesame Street", phone_number: "111-111-1111", currently_doing: "Working in a real estate firm ", education: "School in Israel ", references: nil, additional_info: "Loves to hike and the outdoors ", admin: false, image_url: "https://thumbs.dreamstime.com/b/male-silhoutte-avatar-default-profile-picture-photo-placeholder-vector-illustration-130555183.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
  { first_name: "Riki", last_name: "Irch", email: "riki@example.com", password_digest: "$2a$12$yqOhkO9T9t.vyDsHtDiEd.HumgWsPFnbg3DnT9cZZMALkV72PgxaK", gender: "F", birthday: "2001-02-20", address: "home", phone_number: "israeli", currently_doing: "makeup", education: "shana bet", references: "", additional_info: "", admin: false, image_url: "https://i.ytimg.com/vi/b4d28V5tKC0/maxresdefault.jpg", parents: nil, siblings: nil, shul: nil, summers: nil, height: "5", shadchan_info: nil, looking_for: "Boy", machatonim: nil },
])

# Match.create!([
#   { girl_id: 22, boy_id: 30, girl_approval: false, boy_approval: false },
#   { girl_id: 24, boy_id: 37, girl_approval: false, boy_approval: false },
#   { girl_id: 25, boy_id: 33, girl_approval: false, boy_approval: false },
#   { girl_id: 26, boy_id: 39, girl_approval: false, boy_approval: true },
#   { girl_id: 26, boy_id: 37, girl_approval: false, boy_approval: false },
#   { girl_id: 27, boy_id: 37, girl_approval: false, boy_approval: false },
#   { girl_id: 28, boy_id: 41, girl_approval: true, boy_approval: true },
#   { girl_id: 29, boy_id: 33, girl_approval: false, boy_approval: false },
#   { girl_id: 29, boy_id: 41, girl_approval: false, boy_approval: false },
#   { girl_id: 31, boy_id: 37, girl_approval: true, boy_approval: true },
#   { girl_id: 36, boy_id: 41, girl_approval: true, boy_approval: true },
#   { girl_id: 38, boy_id: 41, girl_approval: true, boy_approval: true },
#   { girl_id: 42, boy_id: 40, girl_approval: false, boy_approval: false },
#   { girl_id: 25, boy_id: 40, girl_approval: true, boy_approval: false },
# ])
